### ISSUE TITLE
Stylesheets need an overhaul

### ISSUE THREAD

**Issue by cynolycus** [cynolycus/cynolycus.github.io#1]
# CSS is kludged together
## Description
In an effort to breeze through the basics of Jekyll,GH-Pages, etc., very little attention was given to doing things (1) correctly or (2) professionally. A great place example of this haste in in our CSS, which is a mixture of the Minima theme and awkward, poorly implemented overrides. In addition, the current version of syntax highlighting and code fencing tries exceptionally hard to be as gruelling and manual as possible for the sake of experimenting with Kramdown's ADLs.

While there's nothing at all wrong with the pre-built Jekyll themes available, a personal portfolio ought to be representative of its creator's own vision and efforts. Rather than finding a basic theme creating significant customizations around it, there's little harm in starting from scratch. 

Conversely, the problem of syntax highlighting has already been solved by much more intelligent and dedicated minds than myself in GH-Pages' built-in [rouge](https://github.com/rouge-ruby/rouge) highlighter. 

## Tasks
- [x] Remove the dependency on Minima and consolidate desirable aspects of the current look-and-feel to cleaner, thought-out SCSS.
- [x] Simplify the current approach to syntax highlighting by relying on simple code fencing instead of complex markdown and manual class assignments.
- [x] Where desirable, use SCSS to generate language-specific highlighting overrides that do not require altering the natural flow of using Kramdown for code blocks.
- [x] Keep it simple.

**Comment by cynolycus** [comment]
We've got an MVP in this regard, but there's certainly room for improvement in cleaning things up. More to come.
