### ISSUE TITLE
UX Redesign

### ISSUE THREAD

**Issue by cynolycus** [cynolycus/cynolycus.github.io#2]
# UX Redesign
## Description
Rather than throw paint at the wall and see what turns up (which was, admittedly, a large part of the method until now), let's take a more structured 
approach going forward and create a site that is both functional and creative. The end goal is to have a portfolio which not only points users to other projects and undertakings (such as the blog), but itself represents solid web design principles.

Opinions are welcome.

## Tasks
- [x] Draft one or more rough concepts for the final appearance and flow of this site.
- [ ] Locate and analyze high-quality examples of other websites which embody those desired characteristics. Take specific note of what's done well, and what could be done better (and how!), particularly in the context of this project.
- [ ] Outline the specific strategy for the re-design, creating separate Issues for each major component in order to track its progress.
